# Generated by Django 4.0.3 on 2022-11-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_projectid_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectId',
            field=models.CharField(max_length=255),
        ),
    ]
